spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 3ACQgCp9kTRoaZnf6k_o
            client-secret: ZcAG4NGML1
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email, gender, age
            client-name: naver
          kakao:
            client-id: 15ab8aad0d60629c5192762fe2442a03
            client-secret: uZg7f415S2RbrD6E0qihaXW8Y6ha4wMF
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope: account_email, gender, age_range
            client-name: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

